jobs:
- job: windows
  strategy:
    maxParallel: 2
    matrix:
      x64:
        BUILD_ARCH: x64
        PLATFORM: x64
        RID: win7-x64
      x86:
        BUILD_ARCH: x86
        PLATFORM: Win32
        RID: win7-x86
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      git clone https://github.com/microsoft/vcpkg
      vcpkg\bootstrap-vcpkg.bat
    displayName: Install vcpkg
  - script: |
      vcpkg\vcpkg version
      vcpkg\vcpkg integrate install
      set VCPKG_BUILD_TYPE=release
      vcpkg\vcpkg install libiconv:%BUILD_ARCH%-windows
    displayName: Install libiconv
  - task: MSBuild@1
    inputs:
      solution: 'libplist.sln' 
      platform: $(PLATFORM)
      configuration: Release
    displayName: 'Release build'
  - task: MSBuild@1
    inputs:
      solution: 'libplist.sln' 
      platform: $(PLATFORM)
      configuration: Debug
    displayName: 'Debug build'
  - powershell: |
      Invoke-Pester -Path ".\test" -OutputFormat NUnitXml -OutputFile TestResults.xml -PassThru
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: 'TestResults.xml'
  - script: |
      mkdir %BUILD_ARTIFACTSTAGINGDIRECTORY%\libplist\%RID%\bin\
      mkdir %BUILD_ARTIFACTSTAGINGDIRECTORY%\libplist\%RID%\licenses\
      copy %PLATFORM%\Release\plist.dll %BUILD_ARTIFACTSTAGINGDIRECTORY%\libplist\%RID%\bin\
      copy %PLATFORM%\Release\*.exe %BUILD_ARTIFACTSTAGINGDIRECTORY%\libplist\%RID%\bin\
      copy COPYING.LESSER %BUILD_ARTIFACTSTAGINGDIRECTORY%\libplist\%RID%\licenses\libplist.copyright
    displayName: 'Install'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/libplist/' 
      artifactName: 'libplist'
      publishLocation: 'Container'
    displayName: Publish